/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.isparta.edu.cevaplar;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author drhal
 */
public class Soru1 extends javax.swing.JFrame {

    /**
     * Creates new form Soru1
     */
    
    File file;
    
    public Soru1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBOtomobilDosyası = new javax.swing.JButton();
        jBondalikliAktar = new javax.swing.JButton();
        jBTamSayilariAktar = new javax.swing.JButton();
        jBAktar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBOtomobilDosyası.setText("Otomobil Dosyası");
        jBOtomobilDosyası.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOtomobilDosyasıActionPerformed(evt);
            }
        });

        jBondalikliAktar.setText("Ondalıklı Dosya");
        jBondalikliAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBondalikliAktarActionPerformed(evt);
            }
        });

        jBTamSayilariAktar.setText("Tam Sayı Dosya");
        jBTamSayilariAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTamSayilariAktarActionPerformed(evt);
            }
        });

        jBAktar.setText("Ondalıklı Aktar");
        jBAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAktarActionPerformed(evt);
            }
        });

        jButton1.setText("Tamsayı Aktar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBTamSayilariAktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBondalikliAktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBOtomobilDosyası, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jBOtomobilDosyası, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAktar, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jBondalikliAktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTamSayilariAktar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAktarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
            
        
        try {
            FileWriter fileWriter = new FileWriter(file, false);
            BufferedWriter bWriter = new BufferedWriter(fileWriter); 
            File otoFile=new File("C:\\\\Users\\\\Ali Baran\\\\Desktop\\\\otoliste.txt");
            FileReader fileReader = new FileReader(otoFile); 
            String line; 
            BufferedReader br = new BufferedReader(fileReader); 
            for (int i = 0; i < 147; i++) {
                
                for (int j = 0; j < 1; j++) {
                    line = br.readLine();                      
                System.out.println(line);                  
                bWriter.write(line.substring(13, 16).trim()); 
                }
                 bWriter.newLine();
                
            }
             br.close();
             bWriter.close(); 

        } catch (IOException ex) {
            Logger.getLogger(Soru1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jBAktarActionPerformed

    private void jBOtomobilDosyasıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOtomobilDosyasıActionPerformed
        // TODO add your handling code here:
        
        String f="C:\\Users\\Ali Baran\\Desktop\\otoliste.txt";
        DosyaYolu(f);
            
    }//GEN-LAST:event_jBOtomobilDosyasıActionPerformed

    private void jBondalikliAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBondalikliAktarActionPerformed
        // TODO add your handling code here:
        
         String f="C:\\Users\\Ali Baran\\Desktop\\ondalikli1.txt";
        DosyaYolu(f);
        
    }//GEN-LAST:event_jBondalikliAktarActionPerformed

    private void jBTamSayilariAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTamSayilariAktarActionPerformed
        // TODO add your handling code here:
               
        String f="C:\\Users\\Ali Baran\\Desktop\\tamsayi1.txt";
        DosyaYolu(f);
    }//GEN-LAST:event_jBTamSayilariAktarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            FileWriter fileWriter = new FileWriter(file, false);
            BufferedWriter bWriter = new BufferedWriter(fileWriter); 
            File otoFile=new File("C:\\\\Users\\\\Ali Baran\\\\Desktop\\\\otoliste.txt");
            FileReader fileReader = new FileReader(otoFile); 
            String line; 
            BufferedReader br = new BufferedReader(fileReader); 
            for (int i = 0; i < 147; i++) {
                
                for (int j = 0; j < 1; j++) {
                    line = br.readLine();                      
                System.out.println(line);                  
                bWriter.write(line.substring(25)); 
                }
                 bWriter.newLine();
                
            }
             br.close();
             bWriter.close(); 

        } catch (IOException ex) {
            Logger.getLogger(Soru1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
   public  void DosyaYolu(String f){
   
   file=new File(f);
    
   
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAktar;
    private javax.swing.JButton jBOtomobilDosyası;
    private javax.swing.JButton jBTamSayilariAktar;
    private javax.swing.JButton jBondalikliAktar;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
