/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uygulama1;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Arc2D;

/**
 *
 * @author drhal
 */
public class SeriCizim extends javax.swing.JFrame {

    final static Color kirmizi=Color.red;
    final static Color beyaz=Color.white;
    final static Color siyah=Color.black;
    /**
     * Creates new form SeriCizim
     */
    public SeriCizim() {
        initComponents();
        setBackground(Color.lightGray);
        setForeground(siyah);
        
    }
    
  public void paint(Graphics g) {

        Graphics2D g2 = (Graphics2D)g;

        g2.setPaint(Color.blue);

        Arc2D arc1=new Arc2D.Double(55,55,90,30,90,270,Arc2D.PIE);

        g2.fill(arc1);

        g2.setPaint(siyah);

        Arc2D arc2=new Arc2D.Double(50,50,100,40,90,270,Arc2D.PIE);

        g2.draw(arc2);

        g2.setStroke(new BasicStroke(2f,BasicStroke.CAP_ROUND,

        BasicStroke.JOIN_ROUND,3f,new float[] {10f},0f));

        g2.setPaint(Color.black);

        Arc2D arc3=new Arc2D.Double(50,150,100,40,90,270,Arc2D.PIE);

        g2.draw(arc3);

        GradientPaint kirmizidanbeyaza=new GradientPaint(250,50,kirmizi,350,90,beyaz);

        g2.setPaint(kirmizidanbeyaza);

        Arc2D arc4=new Arc2D.Double(250,50,100,40,90,270,Arc2D.PIE);

        g2.fill(arc4);

        GradientPaint kirmizidanmaviye=new GradientPaint(250,150,kirmizi,350,190,Color.blue);

        g2.setPaint(kirmizidanmaviye);

        Arc2D arc5=new Arc2D.Double(250,150,100,40,90,270,Arc2D.PIE);

        g2.fill(arc5);

        g2.setStroke(new BasicStroke(2f,BasicStroke.CAP_ROUND,

        BasicStroke.JOIN_ROUND,1f,new float[] {5f},0f));

        g2.setPaint(Color.black);

        g2.draw(arc5);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeriCizim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeriCizim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeriCizim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeriCizim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeriCizim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

