/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cevaplar;

import static Cevaplar.BirinciSoruA.Poledrom;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drhal
 */
public class BirinciSoruB extends javax.swing.JFrame {

     DefaultTableModel model=new DefaultTableModel();
     DefaultTableModel modelSonuc=new DefaultTableModel();
    public BirinciSoruB() {
        initComponents();
        jTableKelimeler.setModel(model);
        model.setColumnIdentifiers(new String [] {"Polidrom Kelimeler"});
        
        jTableSonuc.setModel(modelSonuc);
        modelSonuc.setColumnIdentifiers(new String [] {"En Uzun Kelime"});
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaKelime = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKelimeler = new javax.swing.JTable();
        jButtonEkle = new javax.swing.JButton();
        jButtonBul = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSonuc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaKelime.setColumns(20);
        jTextAreaKelime.setRows(5);
        jScrollPane1.setViewportView(jTextAreaKelime);

        jTableKelimeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableKelimeler);

        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jButtonBul.setText("BUL");
        jButtonBul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBulActionPerformed(evt);
            }
        });

        jTableSonuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableSonuc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButtonEkle)))
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jButtonBul)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEkle)))
                .addGap(31, 31, 31)
                .addComponent(jButtonBul)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        // TODO add your handling code here:
        
         String kelime=jTextAreaKelime.getText();
        if (Poledrom(kelime)==true) {
             model.addRow(new String[] {jTextAreaKelime.getText()});
             
        }
        else{
            JOptionPane.showMessageDialog(null, "Bu Polidromik bir kelime değildir." , "Hatalı Giriş ", JOptionPane.ERROR_MESSAGE);
        
        }
        
       
        jTextAreaKelime.setText("");
        
        
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonBulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBulActionPerformed
        // TODO add your handling code here:
       
       
        
      
        
    }//GEN-LAST:event_jButtonBulActionPerformed

     public static boolean Poledrom(String s)
    {   
        if(s.length() == 0 || s.length() == 1)
            return true; 
        if(s.charAt(0) == s.charAt(s.length()-1))
      
        return Poledrom(s.substring(1, s.length()-1));

        
        return false;
    }
    
     public static String EnUzun(String[] kelimeler){
     
        int enUzunIndex=0;
        int maxKelimeSayisi=0;
        String kelime="hata";
 
        
        
        for (int i=0; i<kelimeler.length; i++){
            
	if (kelimeler[i].length() > maxKelimeSayisi)
		{
			enUzunIndex = i;
			maxKelimeSayisi = kelimeler[i].length(); 
                          return  kelimeler[enUzunIndex];
		}
        }
         
        return kelime;
     }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirinciSoruB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirinciSoruB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirinciSoruB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirinciSoruB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BirinciSoruB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBul;
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableKelimeler;
    private javax.swing.JTable jTableSonuc;
    private javax.swing.JTextArea jTextAreaKelime;
    // End of variables declaration//GEN-END:variables
}
