/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.edu.isparta.dosya;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drhal
 */
public class DosyaIcerikGetir extends javax.swing.JFrame {

    /**
     * Creates new form DosyaIcerikGetir
     */
    public DosyaIcerikGetir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBDosyaOku = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTGoster = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBDosyaOku.setText("Dosyadan Oku");
        jBDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDosyaOkuActionPerformed(evt);
            }
        });

        jTGoster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTGoster);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jBDosyaOku, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBDosyaOku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDosyaOkuActionPerformed
        // TODO add your handling code here:
        
        JFileChooser sec=new JFileChooser();
        sec.showOpenDialog(null);
        
        File f=sec.getSelectedFile();
        String dosyaAdi=f.getAbsolutePath();
        
        //bir txt uzantılı dosyamız var. 
        //bu dosya içeriğinde ilk satır , ayraçı ile ayrılmış sütünlar içeriyor.
        //diğer satırlar ise / ayracı ile ayrılmış sutun verileri içeriyor. 
        
        try {
            BufferedReader br=new BufferedReader(new FileReader(f));
            String ilkSatir=br.readLine().trim();
            String[] sutunlar=ilkSatir.split(",");
            
            DefaultTableModel model=(DefaultTableModel)jTGoster.getModel();
            model.setColumnIdentifiers(sutunlar);
            
            //object dizisine aktarmamızdaki amaç nedir?
            Object[] tabloSutunlari=br.lines().toArray();
            
            for (int i = 0; i < tabloSutunlari.length; i++) {
             String satir=tabloSutunlari[i].toString().trim();
             String[] veriSatir=satir.split("/");
             model.addRow(veriSatir);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(DosyaIcerikGetir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBDosyaOkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosyaIcerikGetir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosyaIcerikGetir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosyaIcerikGetir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosyaIcerikGetir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosyaIcerikGetir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDosyaOku;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTGoster;
    // End of variables declaration//GEN-END:variables
}
