/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.isparta.edu.Arayuz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tr.isparta.edu.Services.BolumService;
import tr.isparta.edu.Services.Mesajlar;

/**
 *
 * @author drhal
 */
public class Bolum extends javax.swing.JFrame {

    /**
     * Creates new form Bolum
     */
    public Bolum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldAdi = new javax.swing.JTextField();
        jTextFieldAciklama = new javax.swing.JTextField();
        jTextFieldEposta = new javax.swing.JTextField();
        jButtonEkle = new javax.swing.JButton();
        jButtonSil = new javax.swing.JButton();
        jButtonGuncelle = new javax.swing.JButton();
        jButtonListele = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBolum = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Adı");

        jLabel2.setText("Açıklama");

        jLabel3.setText("Eposta");

        jButtonEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/ekle.png"))); // NOI18N
        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jButtonSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/sil.png"))); // NOI18N
        jButtonSil.setText("Sil");
        jButtonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilActionPerformed(evt);
            }
        });

        jButtonGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/duzenle.png"))); // NOI18N
        jButtonGuncelle.setText("Güncelle");
        jButtonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuncelleActionPerformed(evt);
            }
        });

        jButtonListele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/liste.png"))); // NOI18N
        jButtonListele.setText("Listele");
        jButtonListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeleActionPerformed(evt);
            }
        });

        jTableBolum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı", "Aciklama", "E-posta"
            }
        ));
        jTableBolum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBolumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBolum);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAciklama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEposta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEkle)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonSil)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonGuncelle)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonListele)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAciklama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEkle)
                    .addComponent(jButtonSil)
                    .addComponent(jButtonGuncelle)
                    .addComponent(jButtonListele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTextFieldID.hide();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        // TODO add your handling code here:
        
        String adi=jTextFieldAdi.getText().trim();
        String aciklama=jTextFieldAciklama.getText().trim();
        String eposta=jTextFieldEposta.getText().trim();
        
        new BolumService().BolumEkleme(adi, aciklama, eposta);
        
        Listele();
        Temizle();        
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilActionPerformed
        // TODO add your handling code here:       
        String secilenID=jTextFieldID.getText().trim();
        if(secilenID!=null && secilenID.length()>0){
            int ID=Integer.parseInt(secilenID);
            new BolumService().BolumSilme(ID);
            Listele();
            Temizle();
        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());
        }
    }//GEN-LAST:event_jButtonSilActionPerformed

    private void jTableBolumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBolumMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel)jTableBolum.getModel();
        
        int secilen=jTableBolum.getSelectedRow();
        
        if(secilen>0){
            jTextFieldID.setText(model.getValueAt(secilen, 0).toString());
            jTextFieldAdi.setText(model.getValueAt(secilen,1).toString());
            jTextFieldAciklama.setText(model.getValueAt(secilen,2).toString());
            jTextFieldEposta.setText(model.getValueAt(secilen,3).toString());
            //jTextFieldID.show();
        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());
        }
    }//GEN-LAST:event_jTableBolumMouseClicked

    private void jButtonListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeleActionPerformed
        // TODO add your handling code here:
        Listele();
    }//GEN-LAST:event_jButtonListeleActionPerformed

    private void jButtonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuncelleActionPerformed
        // TODO add your handling code here:
        String secilenID= jTextFieldID.getText().trim();
        
        if (secilenID!=null && secilenID.length()>0) {
            String adi=jTextFieldAdi.getText().trim();
            String aciklama=jTextFieldAciklama.getText().trim();
            String eposta=jTextFieldEposta.getText().trim();
            int ID=Integer.parseInt(secilenID);
            
            new BolumService().BolumGuncelleme(ID, adi, aciklama, eposta);
            
            Listele();
            Temizle();            
        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());  
        }
        
    }//GEN-LAST:event_jButtonGuncelleActionPerformed

    
    public void Temizle(){
        jTextFieldID.setText("");
        jTextFieldAdi.setText("");
        jTextFieldAciklama.setText("");
        jTextFieldEposta.setText("");
    }
    
    public void Listele(){
        DefaultTableModel model=(DefaultTableModel)jTableBolum.getModel();
        new BolumService().BolumGetir(model);
        JOptionPane.showMessageDialog(null, "Veriler Tabloya Getirildi");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bolum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JButton jButtonGuncelle;
    private javax.swing.JButton jButtonListele;
    private javax.swing.JButton jButtonSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBolum;
    private javax.swing.JTextField jTextFieldAciklama;
    private javax.swing.JTextField jTextFieldAdi;
    private javax.swing.JTextField jTextFieldEposta;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
