/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.isparta.edu.Arayuz;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tr.isparta.edu.Services.KitapService;
import tr.isparta.edu.Services.KitapTurService;
import tr.isparta.edu.Services.KitapYazarService;
import tr.isparta.edu.Services.Mesajlar;

/**
 *
 * @author drhal
 */
public class Kitap extends javax.swing.JFrame {

    ArrayList<tr.isparta.edu.DAL.KitapTur> kitapTurListe=new ArrayList<>();
    ArrayList<tr.isparta.edu.DAL.KitapYazar> kitapYazarListe=new ArrayList<>();
    /**
     * Creates new form Kitap
     */
    public Kitap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldISBNo = new javax.swing.JTextField();
        jTextFieldKitapAdi = new javax.swing.JTextField();
        jTextFieldSayfaSayisi = new javax.swing.JTextField();
        jComboBoxKitapTur = new javax.swing.JComboBox<>();
        jComboBoxYazarAdi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEkle = new javax.swing.JButton();
        jButtonGuncelle = new javax.swing.JButton();
        jButtonSil = new javax.swing.JButton();
        jButtonListele = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableSonuc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kitap Veri Giriş Alanı"));

        jTextFieldSayfaSayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSayfaSayisiActionPerformed(evt);
            }
        });

        jComboBoxKitapTur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxYazarAdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("ISBNo");

        jLabel3.setText("Kitap Adı");

        jLabel4.setText("Sayfa Sayısı");

        jLabel5.setText("Kitap Tür");

        jLabel6.setText("Yazar Adı");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldKitapAdi)
                    .addComponent(jTextFieldSayfaSayisi)
                    .addComponent(jComboBoxKitapTur, 0, 185, Short.MAX_VALUE)
                    .addComponent(jComboBoxYazarAdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldID)
                    .addComponent(jTextFieldISBNo))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldISBNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKitapAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSayfaSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxKitapTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxYazarAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jButtonGuncelle.setText("Güncelle");
        jButtonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuncelleActionPerformed(evt);
            }
        });

        jButtonSil.setText("Sil");
        jButtonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilActionPerformed(evt);
            }
        });

        jButtonListele.setText("Listele");
        jButtonListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonEkle)
                .addGap(36, 36, 36)
                .addComponent(jButtonGuncelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonSil)
                .addGap(18, 18, 18)
                .addComponent(jButtonListele)
                .addGap(35, 35, 35))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kitap Bilgileri");

        jTableSonuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBNo", "Kitap Adı", "Sayfa Sayısı", "Yazar Adı", "Kitap Türü"
            }
        ));
        jTableSonuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSonucMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableSonuc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSayfaSayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSayfaSayisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSayfaSayisiActionPerformed

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        // TODO add your handling code here:
        String ISBNo=jTextFieldISBNo.getText().trim();
        String kitapAdi=jTextFieldKitapAdi.getText().trim();
        String sayfaSayisi=jTextFieldSayfaSayisi.getText().trim();
        boolean sayfaSayisiKontrol=new Mesajlar().sayisalMi(sayfaSayisi);
        int sayfaSayisiInt=0;
        if(sayfaSayisiKontrol==false){
            JOptionPane.showMessageDialog(null, new Mesajlar().GecerliSayfaSayisiGiriniz());
            return;
        }

        if(sayfaSayisi.length()<=0){
            JOptionPane.showMessageDialog(null, new Mesajlar().SayfaSayisiGiriniz());
            return;
        }else{
            sayfaSayisiInt=Integer.parseInt(sayfaSayisi);
        }

        int kitapTurIndeks=jComboBoxKitapTur.getSelectedIndex();
        if(kitapTurIndeks<=0){
            JOptionPane.showMessageDialog(null, new Mesajlar().KitapTurSeciminiziYapiniz());
            return;
        }

        tr.isparta.edu.DAL.KitapTur kitapTurDeger=kitapTurListe.get(kitapTurIndeks-1);
        //JOptionPane.showMessageDialog(null, kitapTurDeger.getAd()+" "+kitapTurDeger.getID());

        int kitapYazarIndeks=jComboBoxYazarAdi.getSelectedIndex();
        if(kitapYazarIndeks<=0){
            JOptionPane.showMessageDialog(null, new Mesajlar().KitapYazarSeciminiziYapiniz());
            return;
        }

        tr.isparta.edu.DAL.KitapYazar kitapYazarDeger=kitapYazarListe.get(kitapYazarIndeks-1);
        //JOptionPane.showMessageDialog(null, kitapYazarDeger.getAd()+" "+kitapYazarDeger.getSoyad()+" "+kitapYazarDeger.getID());

        KitapService kitap=new KitapService();
        kitap.Ekleme(ISBNo, kitapAdi, sayfaSayisiInt, kitapYazarDeger.getID(), kitapTurDeger.getID());

        Listele();
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuncelleActionPerformed
        // TODO add your handling code here:

        //güncelleme
    }//GEN-LAST:event_jButtonGuncelleActionPerformed

    private void jButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilActionPerformed
        // TODO add your handling code here:

        //silme
    }//GEN-LAST:event_jButtonSilActionPerformed

    private void jButtonListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeleActionPerformed
        // TODO add your handling code here:

        Listele();
    }//GEN-LAST:event_jButtonListeleActionPerformed

    private void jTableSonucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSonucMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model=(DefaultTableModel)jTableSonuc.getModel();
        int secilen=jTableSonuc.getSelectedRow();

        jTextFieldID.setText(model.getValueAt(secilen,0).toString());
        jTextFieldISBNo.setText(model.getValueAt(secilen,1).toString());
        jTextFieldKitapAdi.setText(model.getValueAt(secilen,2).toString());
        jTextFieldSayfaSayisi.setText(model.getValueAt(secilen, 3).toString());

        int ID=Integer.parseInt(model.getValueAt(secilen,0).toString());
        int[] kitapYazarTur=new KitapService().GetKitapYazarTurByID(ID);

        int kitapYazarIndeks=0, kitapTurIndeks=0;

        for (int i = 0; i < kitapYazarListe.size(); i++) {
            if(kitapYazarListe.get(i).getID()==kitapYazarTur[0])   {
                //JOptionPane.showMessageDialog(null, kitapYazarListe.get(i).getID());
                kitapYazarIndeks=i;
                break;
            }
        }

        for (int i = 0; i < kitapTurListe.size(); i++) {
            if(kitapTurListe.get(i).getID()==kitapYazarTur[1]){
                kitapTurIndeks=i;
                //JOptionPane.showMessageDialog(null, kitapTurListe.get(i).getID());
                break;
            }
        }

        jComboBoxYazarAdi.setSelectedIndex(kitapYazarIndeks+1);
        jComboBoxKitapTur.setSelectedIndex(kitapTurIndeks+1);

    }//GEN-LAST:event_jTableSonucMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTextFieldID.hide();
        
        KitapYazarService kitapYazar=new KitapYazarService();
        DefaultComboBoxModel model=(DefaultComboBoxModel)jComboBoxYazarAdi.getModel();
        kitapYazarListe=kitapYazar.Yukle(model);
        
        KitapTurService kitapTur=new KitapTurService();
        DefaultComboBoxModel modelTur=(DefaultComboBoxModel)jComboBoxKitapTur.getModel();
        kitapTurListe=kitapTur.Yukle(modelTur);
        
        Listele();
    }//GEN-LAST:event_formWindowOpened

    
     public void Listele(){        
        DefaultTableModel model=(DefaultTableModel)jTableSonuc.getModel();
        model=new KitapService().Getir(model);

        Temizle();
    }
    
     public void Temizle(){
        jTextFieldID.setText("");
        jTextFieldISBNo.setText("");
        jTextFieldKitapAdi.setText("");
        jTextFieldSayfaSayisi.setText("");
        jComboBoxKitapTur.setSelectedIndex(0);
        jComboBoxYazarAdi.setSelectedIndex(0);        
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JButton jButtonGuncelle;
    private javax.swing.JButton jButtonListele;
    private javax.swing.JButton jButtonSil;
    private javax.swing.JComboBox<String> jComboBoxKitapTur;
    private javax.swing.JComboBox<String> jComboBoxYazarAdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableSonuc;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldISBNo;
    private javax.swing.JTextField jTextFieldKitapAdi;
    private javax.swing.JTextField jTextFieldSayfaSayisi;
    // End of variables declaration//GEN-END:variables
}
