/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.isparta.edu.Arayuz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tr.isparta.edu.Services.KitapYazarService;
import tr.isparta.edu.Services.Mesajlar;

/**
 *
 * @author drhal
 */
public class KitapYazar extends javax.swing.JFrame {

    /**
     * Creates new form KitapYazar
     */
    public KitapYazar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuncelle = new javax.swing.JButton();
        jButtonListele = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKitapYazar = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldAdi = new javax.swing.JTextField();
        jTextFieldSoyadi = new javax.swing.JTextField();
        jTextFieldKimlikNo = new javax.swing.JTextField();
        jButtonEkle = new javax.swing.JButton();
        jButtonSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/duzenle.png"))); // NOI18N
        jButtonGuncelle.setText("Güncelle");
        jButtonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuncelleActionPerformed(evt);
            }
        });

        jButtonListele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/liste.png"))); // NOI18N
        jButtonListele.setText("Listele");
        jButtonListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeleActionPerformed(evt);
            }
        });

        jLabel1.setText("Adı");

        jTableKitapYazar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı", "Soyadı", "TC Kimlik"
            }
        ));
        jTableKitapYazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKitapYazarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKitapYazar);

        jLabel2.setText("Soyadı");

        jLabel3.setText("TC Kimlik No");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jButtonEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/ekle.png"))); // NOI18N
        jButtonEkle.setText("Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jButtonSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/isparta/edu/Images/sil.png"))); // NOI18N
        jButtonSil.setText("Sil");
        jButtonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEkle)
                        .addGap(90, 90, 90)
                        .addComponent(jButtonSil)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonGuncelle)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonListele)))
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKimlikNo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(414, 414, 414))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKimlikNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEkle)
                    .addComponent(jButtonSil)
                    .addComponent(jButtonGuncelle)
                    .addComponent(jButtonListele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuncelleActionPerformed
        // TODO add your handling code here:
       
        String secilenID= jTextFieldID.getText().trim();
        
        if (secilenID!=null && secilenID.length()>0) {
            String adi=jTextFieldAdi.getText().trim();
            String soyadi=jTextFieldSoyadi.getText().trim();
            String kimlikNo=jTextFieldKimlikNo.getText().trim();
            
            
            int ID=Integer.parseInt(secilenID);
            
            new KitapYazarService().Guncelleme(ID, adi, soyadi,kimlikNo);
            
            Listele();
            
            Temizle();              
        }
    }//GEN-LAST:event_jButtonGuncelleActionPerformed

    private void jButtonListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeleActionPerformed
        // TODO add your handling code here:
        Listele();
        Temizle();
    }//GEN-LAST:event_jButtonListeleActionPerformed

    private void jTableKitapYazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKitapYazarMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTableKitapYazar.getModel();
        int secilen=jTableKitapYazar.getSelectedRow();
        
       jTextFieldID.setText(model.getValueAt(secilen,0).toString());
       jTextFieldAdi.setText(model.getValueAt(secilen,1).toString());
       jTextFieldSoyadi.setText(model.getValueAt(secilen,2).toString());
       jTextFieldKimlikNo.setText(model.getValueAt(secilen,3).toString());
    }//GEN-LAST:event_jTableKitapYazarMouseClicked

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        // TODO add your handling code here:
        String adi=jTextFieldAdi.getText().trim();
        String soyadi=jTextFieldSoyadi.getText().trim();
        String kimlikNo=jTextFieldKimlikNo.getText().trim();
        
        new KitapYazarService().Ekleme(adi, soyadi, kimlikNo);        
        
        Listele();
        Temizle();
    }//GEN-LAST:event_jButtonEkleActionPerformed

    
    public void Temizle(){
        jTextFieldID.setText("");
        jTextFieldAdi.setText("");
        jTextFieldSoyadi.setText("");
        jTextFieldKimlikNo.setText("");
    }
    
    private void jButtonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSilActionPerformed
        // TODO add your handling code here:
       String secilenID= jTextFieldID.getText().trim();
        if (secilenID!=null && secilenID.length()>0) {  
            int ID=Integer.parseInt(secilenID);
            
            new KitapYazarService().Silme(ID);
            
            Listele();
            Temizle();            
            
        }else{
            JOptionPane.showMessageDialog(null, new Mesajlar().SatirSeciniz());  
        }
    }//GEN-LAST:event_jButtonSilActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
        jTextFieldID.hide();
    }//GEN-LAST:event_formWindowOpened

    public void Listele(){
        DefaultTableModel model=(DefaultTableModel)jTableKitapYazar.getModel();
        new KitapYazarService().Getir(model);        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapYazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapYazar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEkle;
    private javax.swing.JButton jButtonGuncelle;
    private javax.swing.JButton jButtonListele;
    private javax.swing.JButton jButtonSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKitapYazar;
    private javax.swing.JTextField jTextFieldAdi;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldKimlikNo;
    private javax.swing.JTextField jTextFieldSoyadi;
    // End of variables declaration//GEN-END:variables
}
