/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uygulama2;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author drhal
 */
public class kontrolkutusu extends javax.swing.JFrame {

    
    int normalFont, kalinFont, italikFont;
    String s="";
    
    int kirmizi, yesil, mavi;
    public Color renk;
    public Color renk1;
    public Color renk2;
    /**
     * Creates new form kontrolkutusu
     */
    public kontrolkutusu() {
        initComponents();
        
        s="Bu yazının sitilini değiştiriniz:";
        italikFont=Font.PLAIN;
        kalinFont=Font.PLAIN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEkran = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jCKallin = new javax.swing.JCheckBox();
        jCItalik = new javax.swing.JCheckBox();
        jBRenkDegistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");

        jCKallin.setText("Kalın");
        jCKallin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCKallinStateChanged(evt);
            }
        });
        jCKallin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCKallinActionPerformed(evt);
            }
        });

        jCItalik.setText("İtalik");
        jCItalik.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCItalikStateChanged(evt);
            }
        });
        jCItalik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCItalikActionPerformed(evt);
            }
        });

        jBRenkDegistir.setText("Renk Değiştir");
        jBRenkDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRenkDegistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEkranLayout = new javax.swing.GroupLayout(jPEkran);
        jPEkran.setLayout(jPEkranLayout);
        jPEkranLayout.setHorizontalGroup(
            jPEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEkranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEkranLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCKallin))
                    .addGroup(jPEkranLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jBRenkDegistir, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCItalik)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPEkranLayout.setVerticalGroup(
            jPEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEkranLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jBRenkDegistir)
                .addGap(18, 18, 18)
                .addGroup(jPEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCKallin)
                    .addComponent(jCItalik))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPEkran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPEkran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCKallinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCKallinStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCKallinStateChanged

    private void jCItalikStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCItalikStateChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jCItalikStateChanged

    private void jCKallinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCKallinActionPerformed
        // TODO add your handling code here:
        kalinFont=Font.BOLD;
        italikFont=Font.PLAIN;
        
        jTextField1.setFont(new Font("TimesRoman",kalinFont+italikFont,14));
        jCItalik.setSelected(false);
    }//GEN-LAST:event_jCKallinActionPerformed

    private void jCItalikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCItalikActionPerformed
        // TODO add your handling code here:
           italikFont=Font.ITALIC;
        kalinFont=Font.PLAIN;
        jTextField1.setFont(new Font("TimesRoman",kalinFont+italikFont,14));
        jCKallin.setSelected(false);
    }//GEN-LAST:event_jCItalikActionPerformed

    private void jBRenkDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRenkDegistirActionPerformed
        // TODO add your handling code here:
        kirmizi=(int)(255*Math.random());
        yesil=(int)(255*Math.random());
        mavi=(int)(255*Math.random());
        
        renk=new Color(kirmizi, yesil, mavi);
        renk1=new Color(yesil, kirmizi, mavi);
        renk2=new Color(mavi, yesil, kirmizi);
        
        //ekran panelinin içeriği değişiyor. 
        jPEkran.setBackground(renk);
        
        //ana panelin rengi değişiyor.
        setBackground(renk1);
        
        //yazı kutusunun rengini değiştiriyoruz. 
        jTextField1.setBackground(renk2);
    }//GEN-LAST:event_jBRenkDegistirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kontrolkutusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kontrolkutusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kontrolkutusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kontrolkutusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kontrolkutusu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRenkDegistir;
    private javax.swing.JCheckBox jCItalik;
    private javax.swing.JCheckBox jCKallin;
    private javax.swing.JPanel jPEkran;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
